//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenceManager.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMASRAFLAR
    {
        public int MASRAFID { get; set; }
        public string CALISANAD { get; set; }
        public Nullable<short> KATEGORI { get; set; }
        public Nullable<int> FIYAT { get; set; }
    
        public virtual TBLKATEGORILER TBLKATEGORILER { get; set; }
    }
}
